### ISSUE TITLE
Typos in your latest blog post

### ISSUE THREAD

**Issue by alexdowad** [akircanski/akircanski.github.io#1]
Hi, @akircanski. Congratulations on hitting the front page of Hacker News!

I haven't finished reading the post yet, but here are some typos to start with:

- "Symetric" should by "Symmetric"
- "alotted" should be "allotted".
- "email" looks better as "e-mail", though perhaps this is just my personal taste.
- The "Nineties" are abbreviated in English as "90's", not "90ties".

**Comment by alexdowad** [comment]
- "succesful" should be "successful".
- "concievably" should be "conceivably".
- "beaurocratic" should be "bureaucratic".
- "cryptanlaytic" should be "cryptanalytic".
- "try to help best I can" should be "try to help as best I can".

That's all I noticed on a single reading. Again, great post and congratulations.

**Comment by akircanski** [comment]
Thank you Alex! I'll correct them ASAP and also add my email to the blog post as I forgot to include that as well.

**Comment by alexdowad** [comment]
Yeah, that's exactly why I had to open a GitHub issue (instead of just e-mailing you)... :wink: The good thing is that your blog is hosted on GH.

**Comment by akircanski** [comment]
Fixed the grammar, added the link to HN and the e-mail address.
