### ISSUE TITLE
RSS feed links

### ISSUE THREAD

**Issue by iamihalcea** [akircanski/akircanski.github.io#2]
Hey!

I've been following your content - thank you for the excellent write-ups! - but noticed that I can't see your articles in my RSS reader. This seems to be because the article locations use `example.com` as the hostname in your [`feed.xml`](https://akircanski.github.io/feed.xml), potentially coming from the [`_config.yml`](https://github.com/akircanski/akircanski.github.io/blob/53665c9932d766abb6b63756fc35a31ca5445a2c/_config.yml#L7) file.

Thanks again!

**Comment by akircanski** [comment]
Thank you for following my (rather sparse) blog and explaining the problem! Now I modified the `_config.yml` `url` setting, I hope that this fixes the problem. If it doesn't please let me know
